# Generated by Django 4.2.9 on 2024-02-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=100)),
                ("subcategory", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
                ("desc", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/images")),
            ],
        ),
    ]
