# Generated by Django 4.2.9 on 2024-02-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce_app", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="media/images/"),
        ),
    ]
